### ISSUE TITLE
The plugin is not working properly

### ISSUE THREAD

**Issue by andamthe** [smutao/PyVibMS#1]
I had my PyMOL with student license. After the installation of the plugin, I can't get the visualization of the molecule I want but instead something like this:
![image](https://user-images.githubusercontent.com/84575051/119135904-4ba8ed00-ba3f-11eb-8b59-c77887554e08.png)
My friend also used the same input file with exactly the same procedure in his computer and it worked:
![image](https://user-images.githubusercontent.com/84575051/119136025-6ed39c80-ba3f-11eb-820e-14fcffa0a423.png)
I also had him checked all of my procedure and nothing was wrong.
Is the student license a problem, does it limit what I can do?

**Comment by smutao** [comment]
Hello @andamthe, could you please provide your POSCAR/CONTCAR file and OUTCAR file for that system? I can take a look into this. 
You may upload files by dropping them into the text section.

**Comment by andamthe** [comment]
> Hello @andamthe, could you please provide your POSCAR/CONTCAR file and OUTCAR file for that system? I can take a look into this.
> You may upload files by dropping them into the text section.



[OUTCAR.txt](https://github.com/smutao/PyVibMS/files/6524484/OUTCAR.txt)
I converted it to txt here. My friend use this one and it worked properly in his computer. He does not have student license as I have so I am suspecting the limit due to the student license

**Comment by smutao** [comment]
> > Hello @andamthe, could you please provide your POSCAR/CONTCAR file and OUTCAR file for that system? I can take a look into this.
> > You may upload files by dropping them into the text section.
> 
> [OUTCAR.txt](https://github.com/smutao/PyVibMS/files/6524484/OUTCAR.txt)
> I converted it to txt here. My friend use this one and it worked properly in his computer. He does not have student license as I have so I am suspecting the limit due to the student license

Hello @andamthe, thank you for the OUTCAR file. I have reproduced the error on Windows 10 but did not have the same issue on Mac OS. 
I have now modified the code and it should be fixed now. You may download the latest code and reinstall to pymol. Please let me know if the problem persists. Thanks.

**Comment by andamthe** [comment]
> > > Hello @andamthe, could you please provide your POSCAR/CONTCAR file and OUTCAR file for that system? I can take a look into this.
> > > You may upload files by dropping them into the text section.
> > 
> > 
> > [OUTCAR.txt](https://github.com/smutao/PyVibMS/files/6524484/OUTCAR.txt)
> > I converted it to txt here. My friend use this one and it worked properly in his computer. He does not have student license as I have so I am suspecting the limit due to the student license
> 
> Hello @andamthe, thank you for the OUTCAR file. I have reproduced the error on Windows 10 but did not have the same issue on Mac OS.
> I have now modified the code and it should be fixed now. You may download the latest code and reinstall to pymol. Please let me know if the problem persists. Thanks.

I have installed the latest code but the problem persists. Could it be due to the limitation of the license?
What should I do?

**Comment by smutao** [comment]
Hi @andamthe, I checked again and did got the same issue with Windows pymol. Then, I modified the code and it works on my windows 10 pymol-2.5.0 now.

![unnamed](https://user-images.githubusercontent.com/10540422/119379363-02e27580-bc85-11eb-8f83-8700570b5eb7.png)

I feel there is some inconsistency in pymol at different operating systems. Is your friend also using windows pymol or a different version of pymol from yours? (The type of license should have no impact on the use of pyvibms.)

**Comment by andamthe** [comment]
It is working for me now. Thank you very much.
Best regards.

**Comment by andamthe** [comment]
> It is working for me now. Thank you very much.
> Best regards.

**Comment by andamthe** [comment]
> Hi @andamthe, I checked again and did got the same issue with Windows pymol. Then, I modified the code and it works on my windows 10 pymol-2.5.0 now.
> 
> ![unnamed](https://user-images.githubusercontent.com/10540422/119379363-02e27580-bc85-11eb-8f83-8700570b5eb7.png)
> 
> I feel there is some inconsistency in pymol at different operating systems. Is your friend also using windows pymol or a different version of pymol from yours? (The type of license should have no impact on the use of pyvibms.)

My friend also uses Windows 10 and he is using the version with 1 month of free trial

**Comment by smutao** [comment]
Hi @andamthe, I'm glad to hear that this problem is now solved for you. Could you please check the version of the pymol you and your friend are using by checking the "About PyMOL"? The version number could be 2.5.0 or else.

**Comment by andamthe** [comment]
> Hi @andamthe, I'm glad to hear that this problem is now solved for you. Could you please check the version of the pymol you and your friend are using by checking the "About PyMOL"? The version number could be 2.5.0 or else.

I use PyMOL 2.5.0 on Windows and my friend uses PyMOL 2.4.1 on Windows. 
I hope it can help.
Best regards

**Comment by smutao** [comment]
Hi @andamthe, thank you for the information. This could be helpful and I can contact the developers of pymol to report this issue in different versions of pymol.
